### ISSUE TITLE
Feedback: why not use Guard?

### ISSUE THREAD

**Issue by andrewhavens** [pawurb/devloop#3]
Hello Paweł,

I hope it's okay if I leave my feedback here. I came across your blog post how learning Rust changed your Ruby workflow. I saw that you started creating this gem and my first question was "why not use Guard"?

In your blog post you mention that `guard-rspec` is no longer maintained, but I don't think that's true. I know there haven't been any commits in a long time, but that's because "it just works". I've been using it with the latest versions of Rails and RSpec without any issues. Guard continues to be maintained. The `listen` gem that Guard uses was updated 2 weeks ago.

That being said, I wonder if there is still a reason that makes `devloop` different/better than using Guard. I can tell you that the main reason I use Guard is for that immediate feedback loop when doing TDD. If there was a better/faster alternative, I would probably switch. The thing that I don't like about Guard is that you have to add it to your Gemfile. I would prefer to use a tool like this that doesn't require me to add it as a dependency to my project.

Have you considered this use-case? Are there other reasons why you are trying to create something better than Guard?

**Comment by pawurb** [comment]
Hi, my use case is to run only recently changed specs on each file save. I'm not sure if this is supported by guard. I think it will always run all specs for a modified file. But, I only did a brief research so please correct me if I'm wrong.

BTW I'll add a feature to run devloop without including it in the Gemfile. Thanks for suggestion!

**Comment by kupkovski** [comment]
There's a way to run only specific specs, by adding the "focus" filter. 

It's not the ideal solution but it was what I used to do
